### ISSUE TITLE
Production deploy

### ISSUE THREAD

**Issue by zhukovsd** [IT-job-market-analytics/compose-stack#25]
- [x] In each service - create `application-prod.yaml`
  - Replace passwords and secret tokens with env variable placeholders, example - `${MYSQL_PASSWORD}`
- [x] In each service, create `prod` branch (branch out from `dev`)
- [x] Create `docker-compose-prod.yaml` stack - use `prod` Docker images, close all ports (except for web-ui), mount necessary env variables to the services

Example - no public port, mount env variable.
```
  rest-api:
    image: itjobmarketanalytics/rest-api:dev
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
```

We'll be mounting these variables from GitHub secrets using .env file - https://docs.docker.com/compose/environment-variables/set-environment-variables/
